-- Create Students Table
CREATE TABLE IF NOT EXISTS public.students (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    grade_level TEXT,
    notes TEXT
);

-- Create Materials (PDFs) Table
CREATE TABLE IF NOT EXISTS public.materials (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    title TEXT NOT NULL,
    file_path TEXT NOT NULL, -- Path to file in Supabase Storage
    subject TEXT,
    page_count INTEGER
);

-- Create Assessments Table
CREATE TABLE IF NOT EXISTS public.assessments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    title TEXT NOT NULL,
    material_id UUID REFERENCES public.materials(id) ON DELETE CASCADE,
    student_id UUID REFERENCES public.students(id) ON DELETE CASCADE,
    questions JSONB NOT NULL, -- Structure generated by AI
    answer_key JSONB NOT NULL,
    score INTEGER,
    total_points INTEGER
);

-- Enable RLS (Row Level Security) - set to completely open for now as this is a single tutor app
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assessments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all operations for students" ON public.students FOR ALL USING (true);
CREATE POLICY "Allow all operations for materials" ON public.materials FOR ALL USING (true);
CREATE POLICY "Allow all operations for assessments" ON public.assessments FOR ALL USING (true);

-- Set up Realtime
alter publication supabase_realtime add table public.students;
alter publication supabase_realtime add table public.materials;
alter publication supabase_realtime add table public.assessments;
